import unittest
from ipvanish import get_countries, get_country_cities, get_city_servers

class TestConfigFunctions(unittest.TestCase):

    def setUp(self):
        self.cfgdir = './configs'

    def test_returns_thismany(self):
        self.assertEqual(len(get_countries(self.cfgdir)), 52)

    def test_get_country_cities_returns_amt(self):
        self.assertEqual(len(get_country_cities('CH')), 1)
        self.assertEqual(len(get_country_cities('MD')), 1)
        self.assertEqual(len(get_country_cities('SK')), 1)
        self.assertEqual(len(get_country_cities('GR')), 1)
        self.assertEqual(len(get_country_cities('AR')), 1)
        self.assertEqual(len(get_country_cities('PT')), 1)
        self.assertEqual(len(get_country_cities('TW')), 1)
        self.assertEqual(len(get_country_cities('CR')), 1)
        self.assertEqual(len(get_country_cities('CL')), 1)
        self.assertEqual(len(get_country_cities('IT')), 1)
        self.assertEqual(len(get_country_cities('NZ')), 1)
        self.assertEqual(len(get_country_cities('MX')), 1)
        self.assertEqual(len(get_country_cities('IS')), 1)
        self.assertEqual(len(get_country_cities('RO')), 1)
        self.assertEqual(len(get_country_cities('DK')), 1)
        self.assertEqual(len(get_country_cities('UK')), 5)
        self.assertEqual(len(get_country_cities('MY')), 1)
        self.assertEqual(len(get_country_cities('SG')), 1)
        self.assertEqual(len(get_country_cities('IL')), 1)
        self.assertEqual(len(get_country_cities('NG')), 1)
        self.assertEqual(len(get_country_cities('EE')), 1)
        self.assertEqual(len(get_country_cities('CA')), 3)
        self.assertEqual(len(get_country_cities('HU')), 1)
        self.assertEqual(len(get_country_cities('US')), 17)
        self.assertEqual(len(get_country_cities('ZA')), 1)
        self.assertEqual(len(get_country_cities('BR')), 1)
        self.assertEqual(len(get_country_cities('AU')), 5)
        self.assertEqual(len(get_country_cities('LU')), 1)
        self.assertEqual(len(get_country_cities('AE')), 1)
        self.assertEqual(len(get_country_cities('BG')), 1)
        self.assertEqual(len(get_country_cities('CZ')), 1)
        self.assertEqual(len(get_country_cities('IN')), 2)
        self.assertEqual(len(get_country_cities('SE')), 1)
        self.assertEqual(len(get_country_cities('CO')), 1)
        self.assertEqual(len(get_country_cities('FI')), 1)
        self.assertEqual(len(get_country_cities('SI')), 1)
        self.assertEqual(len(get_country_cities('FR')), 3)
        self.assertEqual(len(get_country_cities('AL')), 1)
        self.assertEqual(len(get_country_cities('HR')), 1)
        self.assertEqual(len(get_country_cities('KR')), 1)
        self.assertEqual(len(get_country_cities('PE')), 1)
        self.assertEqual(len(get_country_cities('AT')), 1)
        self.assertEqual(len(get_country_cities('NL')), 1)
        self.assertEqual(len(get_country_cities('NO')), 1)
        self.assertEqual(len(get_country_cities('BE')), 1)
        self.assertEqual(len(get_country_cities('JP')), 1)
        self.assertEqual(len(get_country_cities('DE')), 1)
        self.assertEqual(len(get_country_cities('LV')), 1)
        self.assertEqual(len(get_country_cities('ES')), 2)
        self.assertEqual(len(get_country_cities('RS')), 1)
        self.assertEqual(len(get_country_cities('PL')), 1)
        self.assertEqual(len(get_country_cities('IE')), 1)


    def test_get_city_servers_returns_amt(self):
        self.assertEqual( len( get_city_servers('zrh') ), 12)
        self.assertEqual( len( get_city_servers('kiv') ), 2)
        self.assertEqual( len( get_city_servers('bts') ), 5)
        self.assertEqual( len( get_city_servers('ath') ), 3)
        self.assertEqual( len( get_city_servers('eze') ), 3)
        self.assertEqual( len( get_city_servers('lis') ), 5)
        self.assertEqual( len( get_city_servers('tpe') ), 2)
        self.assertEqual( len( get_city_servers('sjo') ), 4)
        self.assertEqual( len( get_city_servers('scl') ), 5)
        self.assertEqual( len( get_city_servers('lin') ), 26)
        self.assertEqual( len( get_city_servers('akl') ), 4)
        self.assertEqual( len( get_city_servers('gdl') ), 4)
        self.assertEqual( len( get_city_servers('rkv') ), 2)
        self.assertEqual( len( get_city_servers('otp') ), 3)
        self.assertEqual( len( get_city_servers('cph') ), 12)
        self.assertEqual( len( get_city_servers('lhr') ), 4)
        self.assertEqual( len( get_city_servers('gla') ), 6)
        self.assertEqual( len( get_city_servers('bhx') ), 20)
        self.assertEqual( len( get_city_servers('man') ), 18)
        self.assertEqual( len( get_city_servers('lon') ), 69)
        self.assertEqual( len( get_city_servers('kul') ), 10)
        self.assertEqual( len( get_city_servers('sin') ), 29)
        self.assertEqual( len( get_city_servers('tlv') ), 8)
        self.assertEqual( len( get_city_servers('los') ), 5)
        self.assertEqual( len( get_city_servers('tll') ), 4)
        self.assertEqual( len( get_city_servers('yvr') ), 6)
        self.assertEqual( len( get_city_servers('yul') ), 29)
        self.assertEqual( len( get_city_servers('tor') ), 20)
        self.assertEqual( len( get_city_servers('bud') ), 4)
        self.assertEqual( len( get_city_servers('mia') ), 67)
        self.assertEqual( len( get_city_servers('sjc') ), 54)
        self.assertEqual( len( get_city_servers('hou') ), 46)
        self.assertEqual( len( get_city_servers('atl') ), 128)
        self.assertEqual( len( get_city_servers('den') ), 33)
        self.assertEqual( len( get_city_servers('bos') ), 77)
        self.assertEqual( len( get_city_servers('lax') ), 84)
        self.assertEqual( len( get_city_servers('sea') ), 30)
        self.assertEqual( len( get_city_servers('chi') ), 102)
        self.assertEqual( len( get_city_servers('clt') ), 40)
        self.assertEqual( len( get_city_servers('dal') ), 101)
        self.assertEqual( len( get_city_servers('phx') ), 35)
        self.assertEqual( len( get_city_servers('cvg') ), 21)
        self.assertEqual( len( get_city_servers('nyc') ), 150)
        self.assertEqual( len( get_city_servers('las') ), 36)
        self.assertEqual( len( get_city_servers('msy') ), 54)
        self.assertEqual( len( get_city_servers('iad') ), 106)
        self.assertEqual( len( get_city_servers('jnb') ), 6)
        self.assertEqual( len( get_city_servers('gru') ), 13)
        self.assertEqual( len( get_city_servers('adl') ), 4)
        self.assertEqual( len( get_city_servers('mel') ), 23)
        self.assertEqual( len( get_city_servers('bne') ), 6)
        self.assertEqual( len( get_city_servers('syd') ), 30)
        self.assertEqual( len( get_city_servers('per') ), 6)
        self.assertEqual( len( get_city_servers('lux') ), 7)
        self.assertEqual( len( get_city_servers('dxb') ), 2)
        self.assertEqual( len( get_city_servers('sof') ), 4)
        self.assertEqual( len( get_city_servers('prg') ), 16)
        self.assertEqual( len( get_city_servers('del') ), 2)
        self.assertEqual( len( get_city_servers('bom') ), 6)
        self.assertEqual( len( get_city_servers('sto') ), 30)
        self.assertEqual( len( get_city_servers('bog') ), 5)
        self.assertEqual( len( get_city_servers('hel') ), 12)
        self.assertEqual( len( get_city_servers('lju') ), 5)
        self.assertEqual( len( get_city_servers('bod') ), 9)
        self.assertEqual( len( get_city_servers('par') ), 26)
        self.assertEqual( len( get_city_servers('mrs') ), 4)
        self.assertEqual( len( get_city_servers('tia') ), 4)
        self.assertEqual( len( get_city_servers('zag') ), 3)
        self.assertEqual( len( get_city_servers('sel') ), 4)
        self.assertEqual( len( get_city_servers('lim') ), 5)
        self.assertEqual( len( get_city_servers('vie') ), 12)
        self.assertEqual( len( get_city_servers('ams') ), 69)
        self.assertEqual( len( get_city_servers('osl') ), 7)
        self.assertEqual( len( get_city_servers('bru') ), 14)
        self.assertEqual( len( get_city_servers('nrt') ), 20)
        self.assertEqual( len( get_city_servers('fra') ), 56)
        self.assertEqual( len( get_city_servers('rix') ), 5)
        self.assertEqual( len( get_city_servers('vlc') ), 4)
        self.assertEqual( len( get_city_servers('mad') ), 30)
        self.assertEqual( len( get_city_servers('beg') ), 3)
        self.assertEqual( len( get_city_servers('waw') ), 8)
        self.assertEqual( len( get_city_servers('dub') ), 14)

